version: '3.3'

services:
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql

    restart: always
    container_name: glpi_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: glpi_db
      MYSQL_USER: glpi
      MYSQL_PASSWORD: 123456
      TZ: America/Sofia


  glpi:
    depends_on:
      - db
    volumes:
      - app_data:/var/www/glpi
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: glpi
    ports:
      - "8001:80"
    restart: always
     
volumes:
    db_data: {}
    app_data: {}

